In [ ]:
# PREGUNTA 1
# La función lineal que da el tiempo de ejecución de un algoritmo (en ms) según
# el tamaño de la lista de n elementos es:
#   T(n) = 3n + 5
# Identificar:
# - Variable independiente
# - Variable dependiente
# - Pendiente
# - Coeficiente de posición

def T(n):
    return 3*n + 5

pendiente = 3                # número que multiplica a n
coef_pos = 5                 # término constante
variable_independiente = "n (tamaño de la lista, número de elementos)"
variable_dependiente = "T(n) (tiempo de ejecución del algoritmo en milisegundos)"

print("Variable independiente:", variable_independiente)
print("Variable dependiente:", variable_dependiente)
print("Pendiente:", pendiente)
print("Coeficiente de posición:", coef_pos)

In [2]:
# PREGUNTA 2
# Con la función T(n) = 3n + 5, interpretar la pendiente.
# La pendiente se puede ver como el cambio en T(n) cuando aumenta en 1 el tamaño n.

def T(n):
    return 3*n + 5

n_actual = 10
n_siguiente = n_actual + 1

diferencia = T(n_siguiente) - T(n_actual)
print("Cambio en el tiempo al aumentar 1 elemento en la lista:", diferencia, "ms")

# Por lo tanto, el tiempo de ejecución del algoritmo aumenta 3 milisegundos por cada elemento adicional en la lista.

Cambio en el tiempo al aumentar 1 elemento en la lista: 3 ms


In [3]:
# PREGUNTA 3
# Calcular el tiempo que tarda el algoritmo para una lista de 101 elementos
# usando la función T(n) = 3n + 5.

def T(n):
    return 3*n + 5

n = 101
tiempo_101 = T(n)
print(f"Para una lista de {n} elementos, el tiempo es {tiempo_101} ms")


Para una lista de 101 elementos, el tiempo es 308 ms


In [ ]:
# PREGUNTA 4
# Datos de la tabla:
# Número de tareas (x):  5, 10, 15, 20
# Costo en dólares f(x): 200, 300, 400, 500
# Se pide encontrar la función lineal f(x) usando numpy.polyfit.

import numpy as np

x = np.array([5, 10, 15, 20])       # número de tareas
y = np.array([200, 300, 400, 500])  # costo en dólares

# f(x) ≈ m*x + b
m, b = np.polyfit(x, y, 1)

print("Pendiente m =", m)
print("Coeficiente de posición b =", b)
print(f"La función aproximada es: f(x) = {m:.0f}*x + {b:.0f}")

# Comprobación con uno de los puntos:
tareas = 10
print("Costo para", tareas, "tareas según la función:", m*tareas + b)

Pendiente m = 20.0
Coeficiente de posición b = 100.00000000000004
La función aproximada es: f(x) = 20*x + 100
Costo para 10 tareas según la función: 300.00000000000006


In [8]:
# PREGUNTA 5
# A inicios de 1985 se funda un club. El modelo se considera hasta inicios de 2013.
# x = 0 corresponde al año 1985 (momento de la fundación).
# Pregunta: ¿cuál es el dominio contextualizado en años?

anio_fundacion = 1985
anio_final = 2013

# x = 0 en 1985, x_final = años transcurridos hasta 2013
x_inicio = 0
x_final = anio_final - anio_fundacion
x_maximo = 8 # Cantidad maximo de y según el grafico
y_maximo = 171

print("Dominio contextualizado: desde", x_inicio, "hasta", x_final, "años")
print("Al transcurrir", x_maximo ,"años, se da la maxima cantidad de socios en el club, con", y_maximo , "miles de socios")


Dominio contextualizado: desde 0 hasta 28 años
Al transcurrir 8 años, se da la maxima cantidad de socios en el club, con 171 miles de socios


In [9]:
# PREGUNTA 6
# El tamaño de una base de datos en TB se modela por:
#   D(t) = 2 * 1.2**t
# donde t es el tiempo en años.
# ¿Cuántos años deben pasar para que D(t) = 20 TB?

import numpy as np
from scipy.optimize import fsolve   # mismo enfoque que usó tu profe

# Modelo de la base de datos
def D(t):
    return 2 * 1.2**t

# Ecuación que queremos que valga 0: D(t) - 20 = 0
def f(t):
    return D(t) - 20

# Valor inicial (punto de partida) para buscar la raíz
t0 = 0  # años

# fsolve busca el t que hace f(t) ≈ 0
solucion = fsolve(f, t0)[0]

print("Años (sin redondear):", solucion)
print("Años (redondeado a la centésima):", round(solucion, 2))
print("Comprobación D(t):", D(solucion))


Años (sin redondear): 12.629253136513444
Años (redondeado a la centésima): 12.63
Comprobación D(t): 20.000000000000387


In [10]:
# PREGUNTA 7
# La cantidad de usuarios de una app se modela por:
#   U(t) = 1000 * e^(0.1 * t)
# donde t está en meses.
# ¿Cuántos usuarios tendrá la app luego de 1 año (12 meses)?
# Aproximar el resultado al entero.

import numpy as np

def U(t):
    return 1000 * np.exp(0.1 * t)

t_meses = 12                 # 1 año = 12 meses
usuarios = U(t_meses)

print("Usuarios (sin redondear):", usuarios)
print("Usuarios (aprox entero):", round(usuarios))

Usuarios (sin redondear): 3320.116922736548
Usuarios (aprox entero): 3320


In [14]:
# PREGUNTA 8
# Sucesión: a_n = 5*n**3 - 2*n
# ¿Cuál es el término de la décima quinta posición? (n = 15)

def a(n):
    return 5*n**3 - 2*n

n = 15
termino_15 = a(n)
print("Termino 15:",termino_15)


Termino 15: 16845


In [15]:
# PREGUNTA 9
# Progresión aritmética:
#   a_1 = 1000
#   diferencia d = 5
# ¿Cuál es a_25?

a1 = 1000   # primer término
d = 5       # diferencia
n = 25      # posición

a_25 = a1 + (n - 1) * d
print("a_25 =", a_25)


a_25 = 1120


In [16]:
# PREGUNTA 10
# Un algoritmo demora en procesar:
# - 1 registro en 2,1 minutos
# - 2 registros en 2,2 minutos
# - 3 registros en 2,3 minutos
# Si se sigue el mismo patrón de crecimiento,
# ¿cuántos registros procesa el algoritmo en 5,6 minutos?

# Formula lineal 
# t(n) = a + b*n

def tiempo(n):
    """Tiempo (en minutos) que tarda el algoritmo en procesar n registros,
    suponiendo un crecimiento lineal como en los datos."""
    return 2 + 0.1 * n  # t(n) = a + b*n

# Queremos encontrar n cuando el tiempo es 5,6 minutos:
t_objetivo = 5.6
n_registros = (t_objetivo - 2) / 0.1

print("Registros procesados en 5,6 minutos:", n_registros)

Registros procesados en 5,6 minutos: 35.99999999999999


In [17]:
# PREGUNTA 11
# Una empresa de software ofrece un servicio de venta y renovación de licencias.
# - El primer año se paga un costo inicial de 250 dólares.
# - Cada año adicional se pagan 50 dólares por la renovación.
# Si la empresa mantiene el servicio por n años,
# ¿cuál es la expresión C_n del costo total pagado?

def C(n):
    """Costo total en dólares después de n años."""
    # Primer año: 250 (se paga una sola vez)
    # Años adicionales: (n - 1) renovaciones de 50 dólares cada una
    return 250 + (n - 1) * 50

# Probamos algunos años para verificar:
for n in [1, 2, 3, 5]:
    print(f"Años = {n}, costo total = {C(n)}")



Años = 1, costo total = 250
Años = 2, costo total = 300
Años = 3, costo total = 350
Años = 5, costo total = 450


In [18]:
# PREGUNTA 12
# Una empresa de almacenamiento en la nube ofrece un plan que INICIA con 10 GB.
# Cada mes, el espacio se DUPLICA (se multiplica por 2).
# S_n representa la cantidad de espacio disponible después de n meses.
# ¿Cuál es la expresión algebraica para S_n?

import numpy as np

def S(n):
    """Espacio disponible en GB después de n meses."""
    # Secuencia: 10, 20, 40, 80, ...
    # Es progresión geométrica de razón 2 que parte en 10.
    # Forma estándar: 10 * 2**n
    # Forma equivalente (la de la alternativa correcta): 20 * 2**(n-1)
    return 20 * 2**(n - 1)

# Mostramos los primeros valores para ver la progresión
for n in range(0, 5):  # 0,1,2,3,4 meses
    print(f"Meses = {n}, espacio = {S(n)} GB")


Meses = 0, espacio = 10.0 GB
Meses = 1, espacio = 20 GB
Meses = 2, espacio = 40 GB
Meses = 3, espacio = 80 GB
Meses = 4, espacio = 160 GB


In [19]:
# PREGUNTA 13
# En una sucesión geométrica:
#   - El cuarto término es 24
#   - El sexto término es 96
# Determinar el valor del noveno término.

# Fórmula general de una sucesión geométrica:
# a_n = a1 * r**(n-1)

a4 = 24
a6 = 96

# a4 = a1 * r**3
# a6 = a1 * r**5
# Dividimos: a6 / a4 = r**2
r2 = a6 / a4          # r al cuadrado
r = r2**0.5           # raíz cuadrada → razón r (positiva)

a1 = a4 / (r**3)      # despejamos el primer término
a9 = a1 * r**8        # noveno término: n = 9 → exponente 8

print("razón r =", r)
print("a1 =", a1)
print("a9 =", a9)

razón r = 2.0
a1 = 3.0
a9 = 768.0


In [21]:
# PREGUNTA 14
# En una tienda nueva:
# - Primera semana: 300 unidades vendidas.
# - Cada semana las ventas aumentan en 40 unidades.
# ¿Cuántas unidades se proyecta vender en TOTAL al cabo de 2 meses?
# (1 mes = 4 semanas → 2 meses = 8 semanas)

# Datos del problema
ventas_semana = 300   # ventas en la primera semana
incremento = 40       # aumento semanal
semanas = 8           # 2 meses = 8 semanas

total = 0             # acumulador

for semana in range(1, semanas + 1):
    # Sumar las ventas de esta semana al total
    total += ventas_semana
    
    # Mostrar para entender qué está pasando (opcional)
    print(f"Semana {semana}: {ventas_semana} unidades")

    # Preparar las ventas de la semana siguiente
    ventas_semana += incremento

print("Total vendido en 2 meses:", total)



Semana 1: 300 unidades
Semana 2: 340 unidades
Semana 3: 380 unidades
Semana 4: 420 unidades
Semana 5: 460 unidades
Semana 6: 500 unidades
Semana 7: 540 unidades
Semana 8: 580 unidades
Total vendido en 2 meses: 3520


In [22]:
# PREGUNTA 15

import numpy as np

# Matriz de calificaciones: filas = estudiantes, columnas = asignaturas
A = np.array([[4.0, 6.7, 3.8],
              [5.3, 4.5, 6.0]])

# Para leer más cómodo:
# A[0,0] → estudiante 1, asignatura 1 = 4.0
# A[1,0] → estudiante 2, asignatura 1 = 5.3
# A[0,1] → estudiante 1, asignatura 2 = 6.7
# A[1,1] → estudiante 2, asignatura 2 = 4.5
# A[0,2] → estudiante 1, asignatura 3 = 3.8
# A[1,2] → estudiante 2, asignatura 3 = 6.0

# Alternativa A:
alt_A = A[1, 0] < A[0, 0]   # ¿estudiante 2 < estudiante 1 en asignatura 1?
print("A:", alt_A)

# Alternativa B:
alt_B = A[0, 0] < 4.0       # ¿estudiante 1 tuvo nota menor que 4.0 en asignatura 1?
print("B:", alt_B)

# Alternativa C:
alt_C = A[1, 1] > 4.0       # ¿estudiante 2 tuvo nota mayor que 4.0 en asignatura 2?
print("C:", alt_C)

# Alternativa D:
alt_D = A[0, 2] > A[1, 2]   # ¿estudiante 1 > estudiante 2 en asignatura 3?
print("D:", alt_D)


A: False
B: False
C: True
D: False


In [23]:
import numpy as np

# PREGUNTA 16
# Matrices de consumo (en GB) para 2 tipos de recursos y varias aplicaciones:
# Servidor A:
A = np.array([[4, 6],
              [8, 5],
              [2, 7]])

# Servidor B:
B = np.array([[1, 7],
              [4, 6],
              [6, 5]])

# Si se quiere obtener la DIFERENCIA de consumo entre ambos servidores
# para cada aplicación y tipo de recurso, ¿qué operación hacemos?

diferencia = A - B   # resta elemento a elemento

print("A - B =\n", diferencia)


A - B =
 [[ 3 -1]
 [ 4 -1]
 [-4  2]]


In [24]:
import numpy as np

A = np.array([[4, 6],
              [8, 5],
              [2, 7]])

B = np.array([[1, 7],
              [4, 6],
              [6, 5]])

S = A + B
print(S)
print("s_21 =", S[1, 0])   # fila 2, columna 1 en notación humana


[[ 5 13]
 [12 11]
 [ 8 12]]
s_21 = 12


In [ ]:
import numpy as np

B = np.array([[1, 7],
              [4, 6],
              [6, 5]])

matriz_multiplicada = B*1.2

print(matriz_multiplicada) 

print(matriz_multiplicada[2][1])



[[1.2 8.4]
 [4.8 7.2]
 [7.2 6. ]]
6.0


In [27]:
# PREGUNTA 19
# La matriz A = (A_ij) indica la cantidad de acciones tipo j, pertenecientes a una empresa,
# que posee el inversionista i.
#
# Por otra parte, la matriz E = (E_ij) detalla el valor unitario de la acción tipo i
# de esta empresa, cotizado en euros, durante el día hábil j de la semana pasada.
#
# Las matrices A y E tienen orden 15x10 y 10x5 respectivamente y se definen por:
#   A_ij = 20 * i * j
#   E_ij = 4 * i + j
#
# ¿En cuánto está evaluado, para el miércoles de la semana pasada,
# el total de acciones que posee en esta empresa el inversionista 8?
# (Miércoles corresponde a j = 3)

import numpy as np

# Tipos de acciones: j = 1..10
tipos = np.arange(1, 11)

# Cantidad de acciones del inversionista 8, para cada tipo j:
# a_8j = 20 * 8 * j
fila_A_8 = 20 * 8 * tipos

# Precio de cada tipo de acción el miércoles (día hábil j = 3):
# e_j3 = 4 * j + 3   (aquí j juega el rol de i en e_ij)
col_E_miercoles = 4 * tipos + 3

# Valor total = suma sobre j de a_8j * e_j3  → producto punto
valor_total = fila_A_8 @ col_E_miercoles

print("Valor total de las acciones del inversionista 8 el miércoles:", valor_total, "euros")
# Resultado: 272800 euros  → 272.800 en las alternativas


Valor total de las acciones del inversionista 8 el miércoles: 272800 euros


In [28]:
import numpy as np

# PREGUNTA 20
# En una empresa hay 2 tipos de dispositivos: estaciones de trabajo (x) y servidores (y).
# Cada estación de trabajo requiere:
#   - 4 GB de RAM
#   - 2 unidades de almacenamiento
# Cada servidor requiere:
#   - 8 GB de RAM
#   - 6 unidades de almacenamiento
#
# La empresa tiene en total:
#   - 72 GB de RAM
#   - 40 unidades de almacenamiento
#
# El sistema que modela la situación es:
#   4x + 8y = 72   (RAM total)
#   2x + 6y = 40   (almacenamiento total)
#
# ¿Cuántas estaciones de trabajo (x) y cuántos servidores (y) se han comprado?

# Matriz de coeficientes
A = np.array([[4, 8],
              [2, 6]])

# Vector de términos independientes
b = np.array([72, 40])

# Resolver el sistema A · [x, y]^T = b
x_sol, y_sol = np.linalg.solve(A, b)

print("Estaciones de trabajo:", x_sol)
print("Servidores:", y_sol)


Estaciones de trabajo: 14.0
Servidores: 2.0


##### RAZONAMIENTOS
1. Identificamos variable independiente, dependiente, pendiente y coeficiente de posición porque la función dada tenía forma lineal. Toda función lineal puede escribirse como y = mx + b. Al compararla con T(n) = 3n + 5, concluimos que n juega el rol de la variable independiente (lo que elegimos: tamaño de la lista), T(n) el de variable dependiente (lo que resulta: tiempo), 3 es la pendiente (cuánto cambia el tiempo al aumentar n en 1) y 5 el coeficiente de posición (el valor inicial cuando n = 0). Usar esta forma estándar permite clasificar rápidamente cada elemento.

2. Interpretamos la pendiente porque, en una recta, la pendiente m siempre representa la razón de cambio: cuánto aumenta (o disminuye) la variable dependiente cuando la independiente aumenta en una unidad. Como en T(n) = 3n + 5 la pendiente es 3, significa que por cada elemento adicional en la lista, el tiempo de ejecución aumenta 3 milisegundos. No puede significar otra cosa, porque es la definición geométrica y funcional de pendiente.

3. Evaluamos T(101) porque preguntaban por el tiempo para una lista de 101 elementos. Como la función ya está definida, el razonamiento correcto es sustituir n por 101. En funciones, “¿qué pasa cuando n vale algo?” siempre se responde reemplazando el valor en la expresión. Así obtuvimos T(101) = 3·101 + 5.

4. Partimos de una tabla número de tareas–costo y detectamos que el costo aumenta siempre en la misma cantidad al aumentar una misma cantidad de tareas; eso indica una relación lineal. Para cualquier relación lineal entre x e y usamos y = mx + b. Calculamos la pendiente m usando dos puntos de la tabla (diferencia de costos dividido por diferencia de tareas) y luego hallamos b usando uno de los puntos en la ecuación. Es el procedimiento estándar para reconstruir la ecuación de una recta a partir de datos.

5. Para el dominio contextualizado analizamos qué representa la variable independiente en el problema: años transcurridos desde 1985 hasta 2013. Eso significa que el tiempo no puede ser negativo (no tendría sentido “antes de fundar el club”) ni pasar del número de años entre 1985 y 2013. Al restar 2013 − 1985 obtuvimos 28. Por eso el dominio va de 0 a 28: todos los valores de tiempo que tienen significado real en el contexto.

6. En el crecimiento exponencial D(t) = 2·1,2^t igualamos la función a 20 porque pedían el tiempo en que se alcanza ese tamaño. Cuando una función está dada explícitamente y queremos encontrar el instante donde toma cierto valor, la estrategia es plantear la ecuación D(t) = valor y resolverla para t. En una función exponencial eso se hace con logaritmos o con un método numérico: en ambos casos la idea central es “despejar t” de una potencia donde aparece como exponente.

7. En el modelo U(t) = 1000·e^{0,1t} simplemente sustituimos t por 12 porque un año corresponde a 12 meses. De nuevo, cuando la pregunta es “¿cuántos usuarios habrá después de tanto tiempo?”, ya no resolvemos una ecuación, solo evaluamos la función en ese valor de tiempo. Usamos la definición de la función y el significado de la variable temporal.

8. En la sucesión aₙ = 5n³ − 2n calculamos el término 15 sustituyendo n = 15. Una sucesión definida por fórmula explícita funciona como una función de n: cada posición n está vinculada a un valor aₙ. Por eso, para obtener el valor de una posición concreta, la regla siempre es reemplazar n por ese número y operar cuidadosamente.

9. En la sucesión con primer término 1000 y diferencia 5 identificamos que es aritmética porque “cada número se incrementa en 5 respecto al anterior”. En progresiones aritméticas se usa la fórmula general aₙ = a₁ + (n − 1)d. Aquí a₁ representa el primer término y d la diferencia constante. Para obtener el término 25, sustituimos n = 25 en esa fórmula. La razón de usar esa fórmula es que resume todas las sumas sucesivas del incremento de una manera compacta.

10. En el problema de registros y tiempo primero observamos el patrón: el tiempo pasa de 2,1 a 2,2 a 2,3; el incremento es siempre 0,1 minuto al sumar un registro. Eso indica otra relación lineal entre número de registros y tiempo. Entonces planteamos t(n) = a + b·n, donde b es el incremento por registro y a el tiempo base. De los datos obtuvimos b = 0,1 y a = 2. Una vez encontrada la función, para saber cuántos registros caben en 5,6 minutos planteamos 5,6 = 2 + 0,1n y despejamos n. La lógica: encontrar la ecuación que describe el crecimiento y luego invertirla para hallar la cantidad correspondiente a un tiempo dado.

11. En el servicio de licencias el costo total tras n años tiene una estructura de “pago inicial + pagos anuales iguales”. El primer año solo se paga la cuota inicial de 250; en los años siguientes se repiten renovaciones de 50. Eso es, de nuevo, una progresión aritmética en los pagos de renovación. Usamos la idea de “primer pago fijo + (n − 1) pagos idénticos” para escribir Cₙ = 250 + (n − 1)·50. No multiplicamos por n la cuota de 50 porque el primer año no se paga renovación, solo desde el segundo en adelante; por eso aparece (n − 1).

12. En el plan de almacenamiento, el espacio “se duplica cada mes”; eso define una progresión geométrica con razón 2. Si el valor inicial es 10 GB, la expresión natural es Sₙ = 10·2ⁿ (considerando n meses después del inicio). La alternativa dada Sₙ = 20·2^{n−1} es algebraicamente equivalente, porque 10·2ⁿ = 10·2·2^{n−1} = 20·2^{n−1}. Usamos un modelo geométrico porque el cambio no es “sumar una cantidad fija” sino “multiplicar siempre por el mismo factor”.

13. En la sucesión geométrica con a₄ y a₆ conocidos usamos la definición aₙ = a₁·r^{n−1}. Como conocemos dos términos distantes, dividimos a₆ entre a₄ para eliminar a₁ y obtener r², ya que a₆/a₄ = r^{5}/r^{3} = r². Eso permite hallar la razón r directamente. Luego, con r conocido, volvemos a una de las ecuaciones (por ejemplo a₄ = a₁·r³) para encontrar a₁. Con a₁ y r calculamos a₉. Este procedimiento de “dividir términos” es estándar en progresiones geométricas para aislar la razón.

14. En las ventas semanales usamos una progresión aritmética porque cada semana se agregan 40 unidades al valor anterior. Para obtener el total vendido en 8 semanas no basta con hallar el último término; necesitamos sumar todos. La forma eficiente de sumar los n primeros términos de una progresión aritmética es la fórmula Sₙ = n/2 · (2a₁ + (n − 1)d), que se basa en emparejar el primer término con el último, el segundo con el penúltimo, etc. Por eso usamos esta fórmula en vez de sumar término por término.

15. En la matriz de calificaciones analizamos cada afirmación leyendo correctamente índices de fila y columna. La matriz tiene dos filas (estudiantes) y tres columnas (asignaturas). Una vez fijada esa interpretación, cada afirmación se verifica comparando los valores correspondientes: por ejemplo, “estudiante 2 en asignatura 2” es el elemento de la segunda fila y segunda columna. El razonamiento es puramente de interpretación de la estructura matricial, no de cálculo.

16. En el problema de consumo de recursos en dos servidores usamos la operación de resta de matrices porque queríamos “diferencia de consumo” servidor A menos servidor B para cada aplicación y cada tipo de recurso. La resta de matrices se define precisamente como la resta elemento a elemento: (A − B){ij} = A{ij} − B_{ij}. No corresponde multiplicar ni transponer si la pregunta es “cuánto más (o menos) consume uno que otro en cada celda”. Por eso la operación adecuada es la resta.

17. Cuando se define S = A + B, cada elemento s_{ij} representa el consumo total de ambos servidores, para la aplicación i y el recurso j. El elemento s_{21} es, por definición, la suma de A_{21} y B_{21}, es decir, “consumo total del recurso 1 en la aplicación 2”. La afirmación del enunciado lo interpretaba como “consumo diario total entre los dos tipos de recursos, para cada servidor”, lo cual es distinto: ahí se estarían sumando columnas (tipos de recursos) y no servidores. Comparamos la definición formal con la frase y detectamos la incompatibilidad, por eso la marcamos como falsa.

18. Para el aumento del 20 % en el consumo de almacenamiento del servidor B en la aplicación 3 usamos el concepto de porcentaje como multiplicación por un factor. Aumentar en 20 % una cantidad significa multiplicarla por 1,2 (100 % + 20 % = 120 %, es decir 1,2 veces el valor original). Primero leímos el consumo original de la entrada correspondiente de la matriz, luego lo multiplicamos por 1,2. Esta es la manera estándar de modelar incrementos porcentuales en matemáticas aplicadas.

19. En la pregunta de acciones y matrices A y E interpretamos que A da cantidades de acciones por tipo y por inversionista, y E da valores unitarios por tipo de acción y día. Para saber el valor total de la cartera de un inversionista en un día específico hay que realizar una suma ponderada: sumar, para cada tipo de acción, “cantidad de acciones de ese tipo × precio de ese tipo ese día”. Esa suma ponderada es exactamente el producto punto entre la fila del inversionista en A y la columna del día en E. Por eso usamos la estructura de producto matricial fila·columna. El uso de las fórmulas a_{ij} y e_{ij} solo nos permitió calcular explícitamente esa fila y esa columna.

20. En el último problema, con estaciones de trabajo y servidores, el sistema de ecuaciones refleja dos restricciones físicas: una para la RAM total y otra para el almacenamiento total. Cada estación y cada servidor aportan cierta cantidad de RAM y de almacenamiento, por lo que el total se escribe como combinación lineal de x (número de estaciones) e y (número de servidores). Eso genera dos ecuaciones lineales con dos incógnitas. Resolver un sistema 2×2 es el método adecuado porque buscamos un par (x, y) que satisfaga simultáneamente ambas condiciones. Utilizamos operaciones algebraicas (simplificar, restar ecuaciones) o un método matricial para encontrar el único par que cumple los dos requisitos de recursos.